export const AES_SECRET_KEY = '#FarmaVidaSecret#'
export const MSG_INVALID_CREDENTIALS = 'Nombre de usuario y/o contraseña incorrectos'
export const LOCAL_USER = 'local_user'
export const LOCAL_ROLE_ADMIN = 'local_role_admin'
export const LOCAL_ROLE_VENDEDOR = 'local_role_vendedor'